// frontend/app/page.tsx
import { BirthForm } from "@/components/BirthForm";

export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-brand-bg to-brand-surface">
      <header className="pt-16 pb-4 text-center">
        <h1 className="font-heading text-5xl font-extrabold tracking-tight text-white">
          Be Better
        </h1>
        <p className="mt-3 text-lg text-brand-muted">
          找到你的天賦方向，成為更好的自己
        </p>
      </header>

      <main className="mx-auto max-w-xl px-4 pb-20">
        <BirthForm />
      </main>
    </div>
  );
}

// frontend/app/app.vue
<template>
  <div
    class="min-h-screen bg-gradient-to-b from-slate-900 to-slate-800 text-white"
  >
    <header class="py-8 text-center">
      <h1 class="text-4xl font-bold tracking-tight">Be Better</h1>
      <p class="mt-2 text-slate-400">找到你的天賦方向，成為更好的自己</p>
    </header>
    <main class="mx-auto max-w-2xl px-4 pb-16">
      <BirthForm />
    </main>
  </div>
</template>
